/* Os valores da
/* O banco de memória é uma lista (JList) de Strings. Cada linha começa com o endereço da memória, seguido do primeiro byte e 
* depois o segundo byte, cada bloco é separado por espaço. Ex: 0001 0000 0101.
* Para pegar um valor da memória basta escrever listMemoryModel.get(index), essa função vai retornar uma string
* Para setar um valor escreva listMemoryModel.set(index, string);
* O banco de registrador também é uma lista(JList) de String e funciona como o banco de memória
* use os métodos listRegisterModel.get(index) e listRegisterModel.set(index, string) para pegar e setar um valor.
* No método initRegister() é possível ver a posição de cada registrador.
* A caixa do código fonte é um campo de texto que pode ser editado. Use o método codigoFonteField.getText() 
* para pegar o texto. Ao carregar um arquivo no botão "Carregar Arquivo" basta setar o texto com o método codigoFonteField.setText().
*/
import javax.naming.ldap.SortControl;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;


public class TelaPrincipal extends javax.swing.JFrame {

    
    private DefaultListModel<String> listMemoryModel = new DefaultListModel<>();
    private DefaultListModel<String> listRegisterModel = new DefaultListModel<>();
    private int Step_Counter = 0;
    private int Step_Counter_memory = 0;
    Memory memory = new Memory();
    VarTable varTable = new VarTable();
    
    public class Memory{
        private int[] palavras = new int[8192];

        public Memory(){
            for(int i = 0; i < 8192; i++){
                this.palavras[i] = 0;
            }  
        }
        public void setPalavra(int data,int position){
            this.palavras[position] = data;
        }

        public int getPalavra(int position){
            return this.palavras[position];
        }
    }

    class LinhaTable {
        String nome;
        int[] reference;
        Boolean status;

        public LinhaTable(String nome, Boolean status, int reference) {
            this.nome = nome;
            this.reference[0] = reference;
            this.status = status;
        }

        public void addReference(int newReference) {
            this.reference[this.reference.length] = newReference; 
        }
    }
    class VarTable {
        private LinhaTable[] tabela;
        int lineCounter;

        public VarTable() {
            this.lineCounter = 0;
        }

        public void addVar(String nome, Boolean status, int reference) {
            tabela[this.lineCounter] = new LinhaTable(nome, status, reference);
            this.lineCounter++;
        }

        public void checkVariable(String varName) {
            for(int i = 0; i < this.tabela.length; i++) {
                if(varName.equals(tabela[i].nome)) {
                    if(tabela[i].status == false) {
                        tabela[i].addReference(Step_Counter_memory);
                    } else if (tabela[i].status == true) {

                    }

                } else {
                    this.addVar(varName, false, Step_Counter_memory);
                }
            }
        }
    }

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        initMemoria();
        initRegister();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        nextStep = new javax.swing.JButton();
        runAll = new javax.swing.JButton();
        codigoFonteLabel = new javax.swing.JLabel();
        memoriaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CodigoFonteField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        terminalLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        entradaTerminalField = new javax.swing.JTextArea();
        enterTerminalButton = new javax.swing.JButton();
        CarregarArquivo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        memoria = new javax.swing.JList<>();
        localizaMemoryField = new javax.swing.JTextField();
        localizaMemoryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registers = new javax.swing.JList<>();
        nextMemoryButton = new javax.swing.JButton();
        prevMomoryButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1, 1));

        nextStep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nextStep.setText("Next Step");
        nextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepActionPerformed(evt);
            }
        });

        runAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        runAll.setText("Run All");
        runAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runAllActionPerformed(evt);
            }
        });

        codigoFonteLabel.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel.setText("Código Fonte");
        codigoFonteLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        memoriaLabel.setBackground(new java.awt.Color(0, 0, 0));
        memoriaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memoriaLabel.setText("Endereços de Memoria");
        memoriaLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        CodigoFonteField.setColumns(20);
        CodigoFonteField.setRows(5);
        CodigoFonteField.setText("read posA\nload posB\nmov  posA posB\nstop\nspace\nspace\nspace\nspace\nspace\npos posA\npos posB\n");
        jScrollPane2.setViewportView(CodigoFonteField);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Registradores");

        terminalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        terminalLabel.setText("Terminal");

        entradaTerminalField.setColumns(20);
        entradaTerminalField.setRows(5);
        entradaTerminalField.setText("523");
        jScrollPane4.setViewportView(entradaTerminalField);

        enterTerminalButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        enterTerminalButton.setText("ENTER");
        enterTerminalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTerminalButtonActionPerformed(evt);
            }
        });

        CarregarArquivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CarregarArquivo.setText("Carregar Arquivo");
        CarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarArquivoActionPerformed(evt);
            }
        });

        memoria.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(memoria);

        localizaMemoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizaMemoryFieldActionPerformed(evt);
            }
        });

        localizaMemoryButton.setText("Localizar memória");
        localizaMemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizaMemoryButtonActionPerformed(evt);
            }
        });

        registers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(registers);

        nextMemoryButton.setText("NEXT");
        nextMemoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMemoryButtonActionPerformed(evt);
            }
        });

        prevMomoryButton.setText("PREV");
        prevMomoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMomoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterTerminalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(terminalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(codigoFonteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(CarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(runAll, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(localizaMemoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(localizaMemoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prevMomoryButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nextMemoryButton))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memoriaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))))
                .addGap(1026, 1026, 1026))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoFonteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(memoriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prevMomoryButton)
                            .addComponent(nextMemoryButton)
                            .addComponent(nextStep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(localizaMemoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(localizaMemoryButton)
                            .addComponent(runAll)))
                    .addComponent(CarregarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterTerminalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(858, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    public void initMemoria(){
        
        String[] memo = new String[4096];
        System.out.println(memory.getPalavra(0));

        listMemoryModel.clear();
        for(int i = 0, j = 0; i<4096; i++,j+=2){
            memo[i] = String.format("%04d", i) + ": " + String.format("%04d", memory.getPalavra(j)) + " " + String.format("%04d", memory.getPalavra(j+1));
            listMemoryModel.addElement(memo[i]);
        }
        memoria.setModel(listMemoryModel);
    }
    
    public void initRegister(){
        
        String[] regis = new String[8];
        
        regis[0] = "AX: 00000000 00000000";
        regis[1] = "DX: 00000000 00000000";
        regis[2] = "SP: 00000000 00000000";
        regis[3] = "SI: 00000000 00000000";
        regis[4] = "IP: 00000000 00000000";
        regis[5] = "SR: 00000000 00000000";
        regis[6] = "CS: 00000000 00000000";
        regis[7] = "DS: 00000000 00000000";
        
        for(int i = 0; i<8; i++){       
            listRegisterModel.addElement(regis[i]);
        }
        registers.setModel(listRegisterModel);
    }
    
    public void setMemoria (String str, int i){
       
        listMemoryModel.set(i, str);
    }
              
    private String[] readTextFromSourceCode(){
        String ArquivoCarregado = CodigoFonteField.getText();
        String[] CommandLine = ArquivoCarregado.split("\n");
        return CommandLine;
    }

    private void nextStepActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String[] sourceCode =  readTextFromSourceCode();
        //pega a linha e separa as instruções
        String[] lineArguments = sourceCode[Step_Counter].split(" ");
    
        for(int i = 0; i < lineArguments.length; i++) {

            //Switch pode virar um método
            switch(lineArguments[0]){
                case "read":
                    memory.setPalavra(12, Step_Counter_memory); 
                break;
            }

            // Checando quantidade de argumentos na linha.
            if(lineArguments.length == 2) {
                varTable.checkVariable(lineArguments[1]);
            } else if (lineArguments.length == 3) {
                varTable.checkVariable(lineArguments[1]);
                varTable.checkVariable(lineArguments[2]);                
            }

        }
        initMemoria();
        Step_Counter++;
        Step_Counter_memory++;
    }                                        

    private void runAllActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here: 
    }                                      

    private void enterTerminalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        String Valor = new String("Testando terminal\nComando de entrada e status serão exibido aqui");
        entradaTerminalField.setText(Valor); // utilizar para a ultima mensagem de comando
    }                                                   

    private void CarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        String ArquivoCarregado = new String("Testando Carregar arquivo\nSerá exibido conteúdo do arquivo aqui...") ;
        CodigoFonteField.setText(ArquivoCarregado);
    }                                               

    private void localizaMemoryFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        String str = localizaMemoryField.getText();
        memoria.ensureIndexIsVisible(Integer.parseInt(str));
    }                                                   

    private void localizaMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        String str = localizaMemoryField.getText();
        memoria.ensureIndexIsVisible(Integer.parseInt(str));
    }                                                    

    private void nextMemoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        int i = memoria.getLastVisibleIndex() + 22;
        memoria.ensureIndexIsVisible(i);
    }                                                

    private void prevMomoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        int i = memoria.getFirstVisibleIndex() - 22;
        memoria.ensureIndexIsVisible(i);
       
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CarregarArquivo;
    private javax.swing.JTextArea CodigoFonteField;
    private javax.swing.JLabel codigoFonteLabel;
    private javax.swing.JButton enterTerminalButton;
    private javax.swing.JTextArea entradaTerminalField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton localizaMemoryButton;
    private javax.swing.JTextField localizaMemoryField;
    private javax.swing.JList<String> memoria;
    private javax.swing.JLabel memoriaLabel;
    private javax.swing.JButton nextMemoryButton;
    private javax.swing.JButton nextStep;
    private javax.swing.JButton prevMomoryButton;
    private javax.swing.JList<String> registers;
    private javax.swing.JButton runAll;
    private javax.swing.JLabel terminalLabel;
    // End of variables declaration                   
}